# Generated by Django 2.2.13 on 2020-12-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('m_star', models.IntegerField()),
                ('short', models.CharField(max_length=400)),
                ('sentiment', models.FloatField()),
            ],
        ),
    ]
